server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://ep-dark-leaf-ashjp3zy.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_3kpsTeGPwmz6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

app:
  jwt:
    secret: mySecretKeyForJWTTokenGenerationThatIsVeryLongAndSecure2024
    expiration: 86400000

stripe:
  secret-key: sk_test_51TndwRCwfjLN94ewU5mRWMSVCTqtxY181ObWdj6cWdZg9EAq7IT6Prv6KpgwWB6o0LW8fzh9DG0Drf5fXMqQETus0080DBAYcx

cors:
  allowed-origins: http://localhost:4200